### ISSUE TITLE
Doesn't work under "Gnome on Wayland"?

### ISSUE THREAD

**Issue by marcvangend** [Keruspe/GPaste#125]
Gpaste doesn't seem to work in a "Gnome on Wayland" session. I did see that the release notes mention "some progress regarding wayland support", so I shouldn't expect too much, but is it correct that is does not work at all at the moment? Or should I change something in the configuration?

System details:
Arch Linux, fully updated
gpaste version: 3.16.2.1
gnome-shell version: 3.16.2
wayland version: 1.8.1
weston version: 1.8.0

**Comment by Keruspe** [comment]
Yep, actually, it is due to several problems:

- first of all, wayland doesn't support selection notification (e.g. "ping me when something new is copied"), or if it does, it's really poorly documented (if you find something about that, I'm all ears)
- When no selection notification is available, GPaste does some active polling, requesting every second "What is available in the clipboard" (the answer should be something like text or image, or ...). Wayland doesn't support that either (or gtk+ hasn't implemented this for wayland yet).

Those two issues make it pretty impossible to do Gpaste work in wayland environment atm without the help of the compositor.

The good news is that mutter 3.17.2 started to sync the X11 (XWayland) clipboard with the wayland one, which will allow me to at least force GPaste to run under XWayland and deal with stuff as it does on traditional X11. It's highly suboptimal but in GPaste 3.18 we should at least have something "kind of working". Hopefully support for selection notification inside a native wayland environment will come soon.

**Comment by marcvangend** [comment]
Thanks for the explanation. At least it wasn't me :-)

Regarding the selection notification, the only documentation I could find is the wl_data_device section on http://wayland.freedesktop.org/docs/html/apa.html, but I bet you already found that yourself.

Obviously this was a know problem for you, so I'll just close this issue. Thanks for GPaste, it's a great tool!

**Comment by Keruspe** [comment]
I think we can keep it open until it's properly working

**Comment by Keruspe** [comment]
Waiting for a better fix, but it now works fine under wayland if you're running gnome-shell.

Closing then, in the hope of a better future fix

**Comment by flashbackpa** [comment]
Sorry but for me it's not working at all....Fedora 22 gpast 3.16.2.1

**Comment by Keruspe** [comment]
gpaste 3.16 won't work on wayland, but gpaste 3.18 will.
I didn't make a release with it yet

**Comment by flashbackpa** [comment]
Ah ok thank you for the quick reply ! :)

**Comment by kghost** [comment]
My gpaste works fine on native wayland apps, but not on Xwayland apps.

is it going to be fixed in 3.18 ?

**Comment by Keruspe** [comment]
@kghost Which version of GPaste and gnome-shell are you running ?

**Comment by kghost** [comment]
Sorry my mistake, it doesn't get any new clips from clipboard.

**Comment by marcvangend** [comment]
Today I upgraded to Gnome shell 3.18. At first sight, Gpaste works perfect now under Wayland. Thanks again.

**Comment by Keruspe** [comment]
Cool :)
It only works thanks to a hack for now, and only when using mutter/gnome-shell, but I plan on working on a new wayland specification which will allow it to work properly.
