### ISSUE TITLE
Extension search-entry style class 

### ISSUE THREAD

**Issue by zagortenay333** [Keruspe/GPaste#137]
I advice against using the `.search-entry` class here. That class targets the entry that is inside the overview, which is usually differently styled from the entries in the dialogs.
Just the default `StEntry` style should be used as it's the one used to style the entries in the modals and popups in most themes.

In my light theme, which has a dark overview theme, this is how it looks:
![screenshot from 2016-01-04 14-40-07](https://cloud.githubusercontent.com/assets/11144630/12090650/31f9ca60-b2f1-11e5-9206-e67c7062e01e.png)

It can be fixed by adding a `.popup-menu .search-entry` combinator, but that's pretty weird.

**Comment by Keruspe** [comment]
Initially I didn't use the .search-entry class, and I was asked to used it *for* compatibility with themes actually.

I'm fully open to doing it some other way though

**Comment by zagortenay333** [comment]
Not sure how it is supposed to help compatibility. StEntry is used inside modal dialogs, which are in most themes identical to popups.

**Comment by zagortenay333** [comment]
Btw, I'm talking about gnome-shell `3.18`. I can't remember what the styles used to look like in previous releases.

**Comment by Keruspe** [comment]
Dropping the search-entry class ends up with the entry being really large, if you find a class which would look nice with the default theme and be compatible with other themes, please make pull request

**Comment by zagortenay333** [comment]
There is not other class here unfortunately. `.search-entry` is used for the overview, while the widget name alone is used for modals.

Btw, how large? Does it look like the one in the modals?

**Comment by Keruspe** [comment]
No, it doesn't look like the one in the modals, it's like 3 or 4 rows high.

If there's no other class, then I prefer to let it as is to have a better default experience with themes, instead of adding one of my own and forcing all theme to specify it if their users use GPaste.

I suggest you do something with `.popup-menu .search-entry` as you said earlier.

If you want to do some testing, the file you need to patch is `/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/searchItem.js`

**Comment by zagortenay333** [comment]
Hmm, that's weird. Will look into it. Thx.
