### ISSUE TITLE
conflicting names ?

### ISSUE THREAD

**Issue by kapouer** [Keruspe/GPaste#145]
Hi,

a debian/testing user reported an issue about
org.gnome.GPaste.service
not being available.
I don't really understand the issue either, it would be nice if you had a moment
to explain what is happening here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822314#15

**Comment by Keruspe** [comment]
I don't have my hand on a computer right now but I think the issue here is
that the systemd service isn't installed. There is not a conflict, the
names are supposed to be the same. They're not installed in the same
location though.

I wonder how we can make that optional. It will work fine when not using
systemd with and without the systemd service installed but will fail on
systemd systems if it isn't.

**Comment by rickysarraf** [comment]
So are these systemd user service files ? 

Because I have similar for another package, redshift, but that gets installed to a common location in:

```
rrs@learner:~$ ls /usr/lib/systemd/user
basic.target                         printer.target@
bluetooth.target@                    pulseaudio.service
busnames.target@                     pulseaudio.socket
dbus.service                         redshift.service
dbus.socket                          shutdown.target@
default.target                       smartcard.target@
exit.target                          sockets.target@
gnome-terminal-server.service        sockets.target.wants/
gvfs-afc-volume-monitor.service      sound.target@
gvfs-daemon.service                  systemd-bus-proxyd.service
gvfs-goa-volume-monitor.service      systemd-bus-proxyd.socket
gvfs-gphoto2-volume-monitor.service  systemd-exit.service
gvfs-metadata.service                telepathy-gabble.service
gvfs-mtp-volume-monitor.service      telepathy-mission-control-5.service
gvfs-udisks2-volume-monitor.service  telepathy-salut.service
obex.service                         timers.target@
paths.target@                        xdg-app-session-helper.service
powerline-daemon.service             xdg-document-portal.service
2016-04-23 / 23:22:17 ♒♒♒  ☺  

rrs@learner:~$ ls /usr/lib/systemd/user/redshift.service 
/usr/lib/systemd/user/redshift.service
2016-04-23 / 23:22:27 ♒♒♒  ☺  
rrs@learner:~$ cat /usr/lib/systemd/user/redshift.service 
[Unit]
Description=Redshift display colour temperature adjustment
Documentation=http://jonls.dk/redshift/
After=display-manager.service

[Service]
ExecStart=/usr/bin/redshift
Restart=always

[Install]
WantedBy=default.target
2016-04-23 / 23:22:29 ♒♒♒  ☺  
```

**Comment by rickysarraf** [comment]
Reading from: http://stackoverflow.com/questions/31702465/how-to-define-a-d-bus-activated-systemd-service

If the dbus service mentions a
```
SystemdServivce=org.foo.service
```

then then there needs to be a relevant systemd service file providing that service. Because dbus will ask systemd for user activation based on the details in that service file.


So, in case of gpaste, I only see the dbus service files.

**Comment by Keruspe** [comment]
That's a packaging issue.

Both the dbus and systemd service files are provided by GPaste

**Comment by kapouer** [comment]
Ok, my bad.
https://anonscm.debian.org/cgit/collab-maint/gpaste.git/commit/?id=f32a752b08a927abb05d9d1f757245741e558d63
will probably fix the issue then.
