### ISSUE TITLE
Blury icon

### ISSUE THREAD

**Issue by bigon** [Keruspe/GPaste#173]
Hi,

org.gnome.GPaste.Ui.desktop file uses the "edit-paste" icon from the
theme but the not a lot of themes (maybe only 2) are providing that icon
in 96x96 or 128x128 size.

That means that in gnome-shell the icon looks blury. Maybe gpaste should
provide a better icon?

**Comment by Keruspe** [comment]
Hi,

I actually use this icon on purpose so that it is better integrated with icon themes than a custom one.
Please report a bug to the icon themes instead as it definitely should be fixed there.

NB: I could give a try to a custom icon, maybe, if someone wanted to design and create one, but I am really bad at design and have never done any image manipulation nor do I plan to, so that person won't be me, but I remain open for suggestions.

**Comment by bigon** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=782007
