### ISSUE TITLE
less intrusive usage avaliable

### ISSUE THREAD

**Issue by albfan** [Keruspe/GPaste#174]
Hi, I'm a profuse parcellite user, making the switch to gpaste, for its indubitable better architecture and design.

My usage most of the time consist on:
- pop up clipboard manager (`<Ctrl><Alt><G>`)
- write text to filter ocurrences (text filter finally works, as it never works on parcellite)
- move around with arrow keys and press enter to select, close clipboard manager, and paste selected entry on last focused window

That last step is what I found missing. Is there a way to configure it or implement it? I can provide a PR with minimal tips about how to do it.

**Comment by Keruspe** [comment]
So, you're using the GPaste UI (not the gnome-shell extension), right?
What you'd like is that when you select something, the window closes automatically?

That's surely feasible. You can try to contribute that feature, which actually sounds nice indeed as that would match the extension behaviour, otherwise I'll do it myself later.

Some hints to implement that:

First, implement a setting for that:
- mimic the images-support boolean settings here https://github.com/Keruspe/GPaste/blob/38568b15bebf021b767ba5b906bf831851172661/data/gsettings/org.gnome.GPaste.gschema.xml.in#L30 with some close-on-select setting
- then mimic what's done for images-support in https://github.com/Keruspe/GPaste/blob/38568b15bebf021b767ba5b906bf831851172661/src/libgpaste/settings/gpaste-settings.h and https://github.com/Keruspe/GPaste/blob/38568b15bebf021b767ba5b906bf831851172661/src/libgpaste/settings/gpaste-settings.c
- then do the same in https://github.com/Keruspe/GPaste/blob/38568b15bebf021b767ba5b906bf831851172661/src/libgpaste/settings-ui/gpaste-settings-ui-stack.c

Then, implement the feature:
In https://github.com/Keruspe/GPaste/blob/38568b15bebf021b767ba5b906bf831851172661/src/libgpaste/ui/gpaste-ui-item.c#L200 we should store the rootwin
https://github.com/Keruspe/GPaste/blob/38568b15bebf021b767ba5b906bf831851172661/src/libgpaste/ui/gpaste-ui-item.c#L40 by calling gtk_window_close on the rootwin stored above

**Comment by albfan** [comment]
Great. Let's go for it

**Comment by Keruspe** [comment]
Fixed in master

**Comment by albfan** [comment]
Thanks! Have to review that commits for next contribution:

https://github.com/Keruspe/GPaste/commit/0923e96becbf6fb9696085d74b35b376d9bd4fc4
https://github.com/Keruspe/GPaste/commit/81b6c3ef46a1d9e40909a663d90a5ec07cdd8f50

**Comment by lkraav** [comment]
I also found the switch from parcellite requiring some extra mental adjustments, but perhaps the next release will fix it up! (y)

**Comment by albfan** [comment]
My two cents https://aur.archlinux.org/packages/gpaste-git

**Comment by Keruspe** [comment]
@lkraav Feel free to open new issues to ask for improvements ;)
