### ISSUE TITLE
insert selection automatically

### ISSUE THREAD

**Issue by albfan** [Keruspe/GPaste#184]
After fantastic #174, another cool thing to add woud be to insert selected text on previously focused window. I'm thinking on <kbd>Shift</kbd>+<kbd>Enter</kbd> instead of <kbd>Enter</kbd> for this behaviour. I checked it has no use now.

**Comment by Keruspe** [comment]
Hi,

This is not doable on wayland, and is not reliably doable in X as it's subject to race conditions and all applications don't use the same mechanisms for pasting.
There used to be a feature similar to that, but it was removed because I prefer not to have a feature to having an unstable and unreliable feature.

**Comment by albfan** [comment]
Good to know

**Comment by Keruspe** [comment]
Fwiw, the only way to do such a thing is to use Xtest (which is a library designed for *testing* X applications) to simulate the user pressing keys.

1) you need to known which keys to press
2) when you ask for keys to be pressed, GPaste is focused, so you have to add a delay long enough for the switching, and short enough so that it won't annoy the user. That delays heavily depends on the user's hardware and on the current load of the computer, which is the really tricky part that makes it not really possible.

**Comment by jtojnar** [comment]
For people coming here from search, more context in https://github.com/Keruspe/GPaste/issues/119.
