### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by rbjorklin** [Keruspe/GPaste#195]
Attached to this issue is a screen shot of gpaste-daemon using 26.7% of system memory on a 32GB machine. My gut tells me this is not quite expected behavior. 
![gpaste-daemon](https://cloud.githubusercontent.com/assets/1704798/23010494/0382abda-f41c-11e6-8646-7e8905c17123.png)

This is happening under Fedora 25.

    $ rpm -q gpaste
    gpaste-3.22.1-1.fc25.x86_64

**Comment by Keruspe** [comment]
Hi

That sounds indeed a little weird.
What is your configured max history size?
Sis you copy real big chunks of text?
Did you copy images (and have images support enabled)?
Can you easily reproduce or what it just one time?
What happens if you run `gpaste-client dr`?

**Comment by rbjorklin** [comment]
I've had my desktop running for 26 days so I'm pretty sure I have copied big chunks of text at least once. I have copied images as well and image support is enabled. Haven't noticed this before so right now I don't have a way of reproducing this. Restarting the daemon reset the memory usage.

    Max element size when displaying: 60
    Max displayed history size: 20
    Max history size: 100
    Max memory usage (MB): 60
    Max text item length: 2147483647
    Min text item length: 1

**Comment by rbjorklin** [comment]
I'm no C developer so not sure if this will be of any use but have you tried [Valgrind](http://valgrind.org/)? There seems to be a [quick-start](http://valgrind.org/docs/manual/quick-start.html) guide 😃

**Comment by Keruspe** [comment]
The settings look really reasonable, you should definitely not reach this level of consumption.
Yup, I'm well aware of valgrind ;)
You're not the first one to complain about a memory leak, and the culprit seems to always be images support. I suggest you disable that if you don't use it (you'll still be able to copy images but they won't be added to the history).
The problem is that no matter how I try, stress-testing images support under valgrind never gives me leaks in GPaste itself, but always in gdk-pixbuf.
I should definitely try and reproduce the gdk-pixbuf leak with a minimal reproducer so that it gets fixed upstream.

**Comment by Keruspe** [comment]
Actually, I just found an actual memleak introduced in GPaste 3.18 due to a misreading of some documentation, in the part that logs what is happening. i just fixed that and I'll release some new GPaste 3.18 3.20 and 3.22 soon.
Given how long you were running GPaste, that could pretty well be it.

There might be another one related to images that I do not fully understand yet, but should be way less critical than this one.

**Comment by Keruspe** [comment]
Releases will be out tomorrow, thanks for the report.
Ping me back if the release still doesn't fix it but it should be way better
