### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by toadlyBroodle** [Keruspe/GPaste#205]
I get these errors when running `./autogen.sh` after cloning from git.

```
src/gi.mk:30: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
Makefile.am:67:   'src/gi.mk' included from here
src/vapi.mk:35: error: ENABLE_VAPIGEN does not appear in AM_CONDITIONAL
Makefile.am:68:   'src/vapi.mk' included from here
Makefile.am:53: error: Libtool library used but 'LIBTOOL' is undefined
```
I get these errors when running `./configure --sysconfdir=/etc
` from extracted gpaste-3.24.0.tar.xz

```
No package 'glib-2.0' found
No package 'gobject-2.0' found
No package 'gio-2.0' found
```

I'm guessing I'm missing dependencies?
OS is stock Ubuntu 16.04.1

**Comment by Keruspe** [comment]
Hi,

To build GPaste from source you'll need deveopment packages of the dependencies, indeed. So for exemple for the error you're seeing from the tarball, you'll need glib-devel (or whatever the correct package name is on ubuntu).
To build it from git it requires even more stuff for the autotools such as vala-devel or vapi devel maybe.
I haven't used ubuntu since 2008 so I don't really know the packages names.
There used to be a README listing those ( https://github.com/Keruspe/GPaste/blob/gpaste-3.18/README.ubuntu ) when there was no official package yet, but it might very well be outdated
