### ISSUE TITLE
Inconsistent copying from GTK2 apps with GNOME 3.24.0 and primary selection

### ISSUE THREAD

**Issue by jdoss** [Keruspe/GPaste#208]
When using gpaste with Fedora 26 Alpha, which ships GNOME Shell 3.24.0, I am seeing inconsistent behavior when using primary selection to copy items into gpaste.

### Steps to reproduce:
Use a GTK2 app such as https://www.sublimetext.com/3 and double click highlight a line. The first selection will work but any subsequent selections after will not add any new items to Gpaste. Also, multi line copies with primary selection do not work. 

If you use a GTk3 app such as gedit or chrome, things work as expected.

**Comment by Keruspe** [comment]
Is it reproducible with other gtk2 apps or only sublime text ?

**Comment by jdoss** [comment]
I have not tested any other gtk2 apps yet, but if you open Sublime Text 3 and highlight something to stick it in primary and then middle click paste it into gedit it it copies fine. It is just not updating in gpaste's history when highlighting text to copy it into primary selection when coming from Sublime Text 3.

**Comment by Keruspe** [comment]
I'll try it out.
Haven't have any issue with other gtk2 apps on my end.

**Comment by jdoss** [comment]
Thanks @Keruspe! I was able to reproduce with the stable and dev builds of ST3. I am using Build 3129 from https://www.sublimetext.com/3dev if you want the exact version I am using now.

**Comment by Keruspe** [comment]
I'm afraid this is not something that can be fixed in GPaste nor any other clipboard manager.
Here is what happens: When you first select something, an "owner-change" event is emitted, to notify software watching the clipboard activity (and the X server) that sublimetext now "owns" the primary selection. When you then select something else, as sublimetext is still the owner of the selection, it thinks that it doesn't have to emit that event, it just changes the data il will send when requested. If I select anything outside of sublimetext then select something in sublimetext again, the owner-change events are emitted as expected.
While this makes sense, this is the blocking point here. There is no other way than using owner-change signal to know that the clipboards/primary selection contnetns has changed. Every application just reemits that signal when the selection changes. Some of them are even to eager at this (for example chromium and emacs emits the signal each time you select a new character) resulting in a flood of signals.
I'm afraid the only soluiton here is for sublimetext to emit the event each time something new is selected.

**Comment by jdoss** [comment]
Thanks for digging into this problem @Keruspe. I just sent your findings into my SublimeText forum post on this problem: https://forum.sublimetext.com/t/st3-with-gnome-3-24-0-and-wayland-text-coping-issues/27342/2
