### ISSUE TITLE
Option to automatically/immediately paste item when selecting it from history view

### ISSUE THREAD

**Issue by jnachtigall** [Keruspe/GPaste#335]
I have been using [Ditto clipboard manager](https://ditto-cp.sourceforge.io/) on Windows 10 for the last 5 years (at work). When I open the history in Ditto with a shortcut (`<Ctrl>+<Shift>+H`) and select an item with `<Enter>` then the History gets closed and the item is automatically pasted. This is the default behaviour and I have never had a case where I selected an item from the History without wanting to paste it immediately.

In **gpaste** I have to press `<Ctlr>+V` afterwards. I have been using gpaste as well for like 5 years (at home, Ubuntu)

I wished gpaste would also paste an item immediately upon selecting in history.

PS Thanks so much for gpaste - could not live without a clipboard manager any more! An absolutely essential tool and I wonder how so many people do not use any.

**Comment by Keruspe** [comment]
There used to be such a feature, but I removed it because it was highly unreliable.

Let me summarize why:
- On wayland, there is currently no way to do that
- On Xorg, the way to do that is using Xtst which is (as its name tells) supposed to only be used in integration tests and such
- Xtst "fakes" keyboard events on the window which has the focus (you cannot select the target window manually), it basically as if you were really typing on your keyboard. GPaste has its own (hidden) window to be able to access the clipboard. We need to play with focus and delays for it to work, and the delay depends a lot on the target machine and how much things are running on it
- There is no consensus as to how to paste something using the keyboard on linux. Some applications will use Ctrl-V, others will use Ctrl-Shift-V, others Shift-Insert, etc, and it's basically impossible to predict which of those we'd want to type.

The feature *could* work on *some* machines, under certain specific conditions, with some specific software, but it would fial in all other scenarii, which I why I decided to drop it

**Comment by jnachtigall** [comment]
I see. Thanks for (taking the time for) the explanation.

**Comment by jtojnar** [comment]
For people coming here from search, more context in https://github.com/Keruspe/GPaste/issues/119.

**Comment by gerdneuman** [comment]
FWIW: [Diodon](https://github.com/diodon-dev/diodon) (yet another clipboard manager for Gnome) has this feature. I switched to Diodon some years ago just for this feature.

**Comment by linusmichelin** [comment]
See https://extensions.gnome.org/extension/779/clipboard-indicator/ . This way you can automatically paste clipboard history on wayland.
