### ISSUE TITLE
Memory Usage too big

### ISSUE THREAD

**Issue by ghost** [Keruspe/GPaste#40]
Using the Gimp (copy/paste) or copying image files in nautilus makes gpaste use all my memory, making the system higly unusable.

If I delete the history nothing changes, I have to kill the process gpasted in order to return to a usable system.

I'm using `$ apt-cache policy gpaste 
gpaste:
  Installato: 2.8.1-1~webupd8~precise
  Candidato:  2.8.1-1~webupd8~precise`
on Ubuntu 12.04 with Gnome-Shell 3.4.1 and the extension `$ apt-cache policy gnome-shell-extensions-gpaste 
gnome-shell-extensions-gpaste:
  Installato: 2.8.1-1~webupd8~precise
  Candidato:  2.8.1-1~webupd8~precise`

**Comment by jacobmischka** [comment]
`gpaste 3.18.3-1` I still to this day have gpaste using 100% of my system's memory whenever it thinks it's convenient. Happens every few days. I don't think this is fixed, or I'm doing something wrong somehow.

**Comment by purpleidea** [comment]
I had to stop using it because of this issue.

**Comment by Keruspe** [comment]
That's really weird, noone complained about that in more than 2 years.

What are your settings?

Do you often copy images?

**Comment by jacobmischka** [comment]
I have track clipboard changes, enable the gnome-shell extension, save history, and image support enabled. I copy images fairly often, usually using the gnome screenshot hotkey to capture a region and save it to clipboard. I'm pretty sure that's what causes it.

It's hard to tell exactly because I don't often notice until a while later when I have no memory left. I just yesterday disabled image support, I'll report back if it happens again since I've done so.

**Comment by Keruspe** [comment]
Ok thanks.

If it's not reproductible with images support disabled, that would explain why not that much people hit it, and why I don't.

**Comment by GabLeRoux** [comment]
Crashed my system, had lots of apps opened, but `gpaste-deamon` was using 4gb before I crash (had glances opened on an other display.

```
gpaste-client --version
GPaste 3.20.1
```
```
aur/gpaste-git 3.20+3+g3503fca-1 (17 | 0.10) [installed]
```

I was using picture support, but looks like I'll turn it off :(

**Comment by jacobmischka** [comment]
Yeah, I haven't had any problems since disabling image support.
